server {
    listen 80;

    # Flask App
    location ^~ /flask/ {
        proxy_pass http://127.0.0.1:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Test API
    location ^~ /api/ {
        proxy_pass http://127.0.0.1:7000/;
    }

    # Static Site
    location ^~ /static/ {
        alias /home/galvan/linux-homelab/static-site/;
        index index.html;
    }
}


